### ISSUE TITLE
Data structure

### ISSUE THREAD

**Issue by imarkonis** [MiRoVaGo/pRecipe#3]
How the data will be stored in R? 

We can create a data.table class, prcp_data that stores different datasets in tidy format. 

Columns: geo_id, dataset, value

Then geo_id, would be another data.table with lat, lon 

This saves 25% of memory, but for every map we should merge the two data tables.

This is crucial as it will be the building block for every function.

**Comment by MiRoVaGo** [comment]
@imarkonis 
I had all the data stored in rasters or bricks (as I read it was most efficient for everything spatial analysis like subsetting or resampling for example)
Struggling with memory myself now will modify the reformatters to store them as data.table instead and then think about the next functions
I think one data.table per data set would be better. Because we do not know if the user will be interested in all the data sets. Also, prior to homogenizing spatiotemporal resolution, units, and so on, I think it'd be more organized being separate

**Comment by imarkonis** [comment]
@MiRoVaGo 

Let me clarify that I am not talking about the stored data, but the data used in the workspace, and give an example of what we are trying to achieve here with some pseudocode:

choose_data(gpm, cru)  
subset_data(1950-2020, my_shapefile)
set_resolution(time = year, space = 5)
graphic_summary [see functions in issue #5]

The trick is to find an efficient way to subseting and/or changing resolution without loading all the data in memory.
